algoritmo "(PASSO 09 – PROCEDIMENTOS) Exercício 90"
// Função :  Desenvolva um algoritmo que leia dois valores pelo teclado e passe esses valores para um procedimento
// Somador() que vai calcular e mostrar a soma entre eles.
// Autor : Paulo Diego
// Data : 26/09/2021
// Seção de Declarações 
var

procedimento somador(x, y:real)
var
inicio
      escreva("A soma de",x," +",y," é",x+y)
FimProcedimento
inicio
// Seção de Comandos
   somador(5, 7)
fimalgoritmo
