algoritmo "(PASSO 04 – REPETIÇÕES ENQUANTO) Exercício 39"
// Função : Faça um algoritmo que mostre na tela a seguinte contagem:
//10 9 8 7 6 5 4 3 Acabou!
// Autor : Paulo Diego
// Data : 12/09/2021
// Seção de Declarações 
var
   cont:inteiro
inicio
// Seção de Comandos
   cont <- 10
   enquanto (cont>=3) faca
            escreva(cont)
            cont <- cont - 1
   fimEnquanto
   escreva(" Acabou!")
 
fimalgoritmo
