algoritmo "(PASSO 04 – REPETIÇÕES ENQUANTO) Exercício 38"
// Função : Escreva um programa que mostre na tela a seguinte contagem:
//6 7 8 9 10 11 Acabou!
// Autor : Paulo Diego
// Data : 12/09/2021
// Seção de Declarações 
var
   cont:inteiro
inicio
// Seção de Comandos
   cont <- 6
   enquanto (cont<=11) faca
            escreva(cont)
            cont <- cont + 1
   fimEnquanto
   escreva(" Acabou!")
 
fimalgoritmo
