algoritmo "(PASSO 04 – REPETIÇÕES ENQUANTO) Exercício 41"
// Função : Desenvolva um programa que mostre na tela a seguinte contagem:
//100 95 90 85 80 ... 0 Acabou!
// Autor : Paulo Diego
// Data : 12/09/2021
// Seção de Declarações 
var
   cont:inteiro
inicio
// Seção de Comandos
   cont <- 100
   enquanto (cont>=0) faca
            escreva(cont)
            cont <- cont - 5
   fimEnquanto
   escreva(" Acabou!")
 
fimalgoritmo
