algoritmo "(PASSO 04 – REPETIÇÕES ENQUANTO) Exercício 40"
// Função : Crie um aplicativo que mostre na tela a seguinte contagem:
//0 3 6 9 12 15 18 Acabou!
// Autor : Paulo Diego
// Data : 12/09/2021
// Seção de Declarações 
var
   cont:inteiro
inicio
// Seção de Comandos
   cont <- 0
   enquanto (cont<=18) faca
            escreva(cont)
            cont <- cont + 3
   fimEnquanto
   escreva(" Acabou!")
 
fimalgoritmo
