algoritmo "(PASSO 02 - CONDIÇÕES BÁSICAS) Exercício 20"
// Função : Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou ÍMPAR.
// Autor : Paulo Diego
// Data : 07/09/2021
// Seção de Declarações 
var
   numero: inteiro
inicio
// Seção de Comandos
   escreva("Digite um número: ")
   leia(numero)
   se (numero%2 = 0) entao
      escreva("O número",numero," é Par!")
   seNao
      escreva("O número",numero," é Impar!")
   fimSe

fimalgoritmo
