algoritmo "(PASSO 01 - SEQUÊNCIAS BÁSICAS) Exercício 2"
// Função : Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
//Ex:
//Qual é o seu nome? João da Silva
//Olá João da Silva, é um prazer te conhecer!
// Autor : Paulo Diego
// Data : 29/08/2021
// Seção de Declarações 
var
   nome: caractere
inicio
// Seção de Comandos
   escreva("Qual é o seu nome? ")
   leia(nome)
   escreva("Olá,",nome,", é um prazer te conhecer!")
   
fimalgoritmo
