algoritmo "(PASSO 07 – REPETIÇÃO COM PARA) Exercício 65"
// Função : Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
// 100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor : Paulo Diego
// Data : 17/09/2021
// Seção de Declarações 
var
cont:inteiro
inicio
// Seção de Comandos
   para cont <- 100 ate 0 passo -10 faca
        escreva(cont)
   fimPara
   escreva(" acabou!")
fimalgoritmo
