algoritmo "(PASSO 07 – REPETIÇÃO COM PARA) Exercício 64"
// Função : Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
// 0 5 10 15 20 25 30 35 40 Acabou!
// Autor : Paulo Diego
// Data : 17/09/2021
// Seção de Declarações 
var
cont:inteiro
inicio
// Seção de Comandos
   para cont <- 0 ate 40 passo 5 faca
        escreva(cont)
   fimPara
   escreva(" acabou!")
fimalgoritmo
