algoritmo "(PASSO 06 – REPETIÇÃO COM FAÇA ENQUANTO) Exercício 61"
// Função : Crie um programa que mostre na tela a seguinte contagem, usando a estrutura “faça enquanto”
// 0 3 6 9 12 15 18 21 24 27 30 Acabou!
// Autor : Paulo Diego
// Data : 16/09/2021
// Seção de Declarações 
var
   cont:inteiro
inicio
// Seção de Comandos
   enquanto (cont<=30) faca
            escreva(cont," ")
            cont <- cont+3
   fimEnquanto
   escreva("Acabou!")
fimalgoritmo
